export interface Surah {
  number: number;
  name: string;
  englishName: string;
  numberOfVerses: number;
}

export const QURAN_SURAH: Surah[] = [
  { number: 1, name: "Al-Fatihah", englishName: "The Opening", numberOfVerses: 7 },
  { number: 2, name: "Al-Baqarah", englishName: "The Cow", numberOfVerses: 286 },
  { number: 3, name: "Ali 'Imran", englishName: "Family of Imran", numberOfVerses: 200 },
  { number: 4, name: "An-Nisa", englishName: "The Women", numberOfVerses: 176 },
  { number: 5, name: "Al-Ma'idah", englishName: "The Table Spread", numberOfVerses: 120 },
  { number: 6, name: "Al-An'am", englishName: "The Cattle", numberOfVerses: 165 },
  { number: 7, name: "Al-A'raf", englishName: "The Heights", numberOfVerses: 206 },
  { number: 8, name: "Al-Anfal", englishName: "The Spoils of War", numberOfVerses: 75 },
  { number: 9, name: "At-Tawbah", englishName: "The Repentance", numberOfVerses: 129 },
  { number: 10, name: "Yunus", englishName: "Jonah", numberOfVerses: 109 },
  { number: 11, name: "Hud", englishName: "Hud", numberOfVerses: 123 },
  { number: 12, name: "Yusuf", englishName: "Joseph", numberOfVerses: 111 },
  { number: 13, name: "Ar-Ra'd", englishName: "The Thunder", numberOfVerses: 43 },
  { number: 14, name: "Ibrahim", englishName: "Abraham", numberOfVerses: 52 },
  { number: 15, name: "Al-Hijr", englishName: "The Rocky Tract", numberOfVerses: 99 },
  { number: 16, name: "An-Nahl", englishName: "The Bee", numberOfVerses: 128 },
  { number: 17, name: "Al-Isra", englishName: "The Night Journey", numberOfVerses: 111 },
  { number: 18, name: "Al-Kahf", englishName: "The Cave", numberOfVerses: 110 },
  { number: 19, name: "Maryam", englishName: "Mary", numberOfVerses: 98 },
  { number: 20, name: "Ta-Ha", englishName: "Ta-Ha", numberOfVerses: 135 },
  { number: 21, name: "Al-Anbiya", englishName: "The Prophets", numberOfVerses: 112 },
  { number: 22, name: "Al-Hajj", englishName: "The Pilgrimage", numberOfVerses: 78 },
  { number: 23, name: "Al-Mu'minun", englishName: "The Believers", numberOfVerses: 118 },
  { number: 24, name: "An-Nur", englishName: "The Light", numberOfVerses: 64 },
  { number: 25, name: "Al-Furqan", englishName: "The Criterion", numberOfVerses: 77 },
  { number: 26, name: "Ash-Shu'ara", englishName: "The Poets", numberOfVerses: 227 },
  { number: 27, name: "An-Naml", englishName: "The Ant", numberOfVerses: 93 },
  { number: 28, name: "Al-Qasas", englishName: "The Stories", numberOfVerses: 88 },
  { number: 29, name: "Al-'Ankabut", englishName: "The Spider", numberOfVerses: 69 },
  { number: 30, name: "Ar-Rum", englishName: "The Romans", numberOfVerses: 60 },
  { number: 31, name: "Luqman", englishName: "Luqman", numberOfVerses: 34 },
  { number: 32, name: "As-Sajdah", englishName: "The Prostration", numberOfVerses: 30 },
  { number: 33, name: "Al-Ahzab", englishName: "The Combined Forces", numberOfVerses: 73 },
  { number: 34, name: "Saba", englishName: "Sheba", numberOfVerses: 54 },
  { number: 35, name: "Fatir", englishName: "Originator", numberOfVerses: 45 },
  { number: 36, name: "Ya-Sin", englishName: "Ya-Sin", numberOfVerses: 83 },
  { number: 37, name: "As-Saffat", englishName: "Those who set the Ranks", numberOfVerses: 182 },
  { number: 38, name: "Sad", englishName: "The Letter Sad", numberOfVerses: 88 },
  { number: 39, name: "Az-Zumar", englishName: "The Troops", numberOfVerses: 75 },
  { number: 40, name: "Ghafir", englishName: "The Forgiver", numberOfVerses: 85 },
  { number: 41, name: "Fussilat", englishName: "Explained in Detail", numberOfVerses: 54 },
  { number: 42, name: "Ash-Shura", englishName: "The Consultation", numberOfVerses: 53 },
  { number: 43, name: "Az-Zukhruf", englishName: "The Ornaments of Gold", numberOfVerses: 89 },
  { number: 44, name: "Ad-Dukhan", englishName: "The Smoke", numberOfVerses: 59 },
  { number: 45, name: "Al-Jathiyah", englishName: "The Crouching", numberOfVerses: 37 },
  { number: 46, name: "Al-Ahqaf", englishName: "The Wind-Curved Sandhills", numberOfVerses: 35 },
  { number: 47, name: "Muhammad", englishName: "Muhammad", numberOfVerses: 38 },
  { number: 48, name: "Al-Fath", englishName: "The Victory", numberOfVerses: 29 },
  { number: 49, name: "Al-Hujurat", englishName: "The Dwellings", numberOfVerses: 18 },
  { number: 50, name: "Qaf", englishName: "The Letter Qaf", numberOfVerses: 45 },
  { number: 51, name: "Adh-Dhariyat", englishName: "The Winnowing Winds", numberOfVerses: 60 },
  { number: 52, name: "At-Tur", englishName: "The Mount", numberOfVerses: 49 },
  { number: 53, name: "An-Najm", englishName: "The Star", numberOfVerses: 62 },
  { number: 54, name: "Al-Qamar", englishName: "The Moon", numberOfVerses: 55 },
  { number: 55, name: "Ar-Rahman", englishName: "The Beneficent", numberOfVerses: 78 },
  { number: 56, name: "Al-Waqi'ah", englishName: "The Inevitable", numberOfVerses: 96 },
  { number: 57, name: "Al-Hadid", englishName: "The Iron", numberOfVerses: 29 },
  { number: 58, name: "Al-Mujadila", englishName: "The Pleading Woman", numberOfVerses: 22 },
  { number: 59, name: "Al-Hashr", englishName: "The Exile", numberOfVerses: 24 },
  { number: 60, name: "Al-Mumtahanah", englishName: "The Examining Woman", numberOfVerses: 13 },
  { number: 61, name: "As-Saff", englishName: "The Ranks", numberOfVerses: 14 },
  { number: 62, name: "Al-Jumu'ah", englishName: "The Congregation", numberOfVerses: 11 },
  { number: 63, name: "Al-Munafiqun", englishName: "The Hypocrites", numberOfVerses: 11 },
  { number: 64, name: "At-Taghabun", englishName: "The Mutual Disillusionment", numberOfVerses: 18 },
  { number: 65, name: "At-Talaq", englishName: "The Divorce", numberOfVerses: 12 },
  { number: 66, name: "At-Tahrim", englishName: "The Prohibition", numberOfVerses: 12 },
  { number: 67, name: "Al-Mulk", englishName: "The Sovereignty", numberOfVerses: 30 },
  { number: 68, name: "Al-Qalam", englishName: "The Pen", numberOfVerses: 52 },
  { number: 69, name: "Al-Haqqah", englishName: "The Reality", numberOfVerses: 52 },
  { number: 70, name: "Al-Ma'arij", englishName: "The Ascending Stairways", numberOfVerses: 44 },
  { number: 71, name: "Nuh", englishName: "Noah", numberOfVerses: 28 },
  { number: 72, name: "Al-Jinn", englishName: "The Jinn", numberOfVerses: 28 },
  { number: 73, name: "Al-Muzzammil", englishName: "The Enshrouded One", numberOfVerses: 20 },
  { number: 74, name: "Al-Muddaththir", englishName: "The Cloaked One", numberOfVerses: 56 },
  { number: 75, name: "Al-Qiyamah", englishName: "The Resurrection", numberOfVerses: 40 },
  { number: 76, name: "Al-Insan", englishName: "Man", numberOfVerses: 31 },
  { number: 77, name: "Al-Mursalat", englishName: "The Emissaries", numberOfVerses: 50 },
  { number: 78, name: "An-Naba", englishName: "The Tidings", numberOfVerses: 40 },
  { number: 79, name: "An-Nazi'at", englishName: "Those who drag forth", numberOfVerses: 46 },
  { number: 80, name: "'Abasa", englishName: "He frowned", numberOfVerses: 42 },
  { number: 81, name: "At-Takwir", englishName: "The Overthrowing", numberOfVerses: 29 },
  { number: 82, name: "Al-Infitar", englishName: "The Cleaving", numberOfVerses: 19 },
  { number: 83, name: "Al-Mutaffifin", englishName: "The Defrauders", numberOfVerses: 36 },
  { number: 84, name: "Al-Inshiqaq", englishName: "The Sundering", numberOfVerses: 25 },
  { number: 85, name: "Al-Buruj", englishName: "The Mansions of the Stars", numberOfVerses: 22 },
  { number: 86, name: "At-Tariq", englishName: "The Morning Star", numberOfVerses: 17 },
  { number: 87, name: "Al-A'la", englishName: "The Most High", numberOfVerses: 19 },
  { number: 88, name: "Al-Ghashiyah", englishName: "The Overwhelming", numberOfVerses: 26 },
  { number: 89, name: "Al-Fajr", englishName: "The Dawn", numberOfVerses: 30 },
  { number: 90, name: "Al-Balad", englishName: "The City", numberOfVerses: 20 },
  { number: 91, name: "Ash-Shams", englishName: "The Sun", numberOfVerses: 15 },
  { number: 92, name: "Al-Layl", englishName: "The Night", numberOfVerses: 21 },
  { number: 93, name: "Ad-Duha", englishName: "The Morning Hours", numberOfVerses: 11 },
  { number: 94, name: "Ash-Sharh", englishName: "The Consolation", numberOfVerses: 8 },
  { number: 95, name: "At-Tin", englishName: "The Fig", numberOfVerses: 8 },
  { number: 96, name: "Al-'Alaq", englishName: "The Clot", numberOfVerses: 19 },
  { number: 97, name: "Al-Qadr", englishName: "The Power", numberOfVerses: 5 },
  { number: 98, name: "Al-Bayyinah", englishName: "The Clear Proof", numberOfVerses: 8 },
  { number: 99, name: "Az-Zalzalah", englishName: "The Earthquake", numberOfVerses: 8 },
  { number: 100, name: "Al-'Adiyat", englishName: "The Courser", numberOfVerses: 11 },
  { number: 101, name: "Al-Qari'ah", englishName: "The Calamity", numberOfVerses: 11 },
  { number: 102, name: "At-Takathur", englishName: "The Rivalry in World Increase", numberOfVerses: 8 },
  { number: 103, name: "Al-'Asr", englishName: "The Declining Day", numberOfVerses: 3 },
  { number: 104, name: "Al-Humazah", englishName: "The Traducer", numberOfVerses: 9 },
  { number: 105, name: "Al-Fil", englishName: "The Elephant", numberOfVerses: 5 },
  { number: 106, name: "Quraysh", englishName: "Quraysh", numberOfVerses: 4 },
  { number: 107, name: "Al-Ma'un", englishName: "The Small Kindnesses", numberOfVerses: 7 },
  { number: 108, name: "Al-Kawthar", englishName: "The Abundance", numberOfVerses: 3 },
  { number: 109, name: "Al-Kafirun", englishName: "The Disbelievers", numberOfVerses: 6 },
  { number: 110, name: "An-Nasr", englishName: "The Divine Support", numberOfVerses: 3 },
  { number: 111, name: "Al-Masad", englishName: "The Palm Fiber", numberOfVerses: 5 },
  { number: 112, name: "Al-Ikhlas", englishName: "The Sincerity", numberOfVerses: 4 },
  { number: 113, name: "Al-Falaq", englishName: "The Daybreak", numberOfVerses: 5 },
  { number: 114, name: "An-Nas", englishName: "Mankind", numberOfVerses: 6 }
];
